resources:
  - ../base/

configMapGenerator:
  - name: agent-config
    files:
      - ./config/grafana-agent.river
  - name: tracing-env
    literals:
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://grafana-agent:4318
