apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-agent
  labels:
    app.k8s.io/name: grafana-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app.k8s.io/name: grafana-agent
  template:
    metadata:
      name: grafana-agent
      labels:
        app.k8s.io/name: grafana-agent
    spec:
      restartPolicy: Always
      serviceAccountName: grafana-agent
      containers:
        - name: grafana-agent
          image: grafana/agent:v0.35.0
          imagePullPolicy: IfNotPresent
          args:
            - run
            - /etc/agent-config/grafana-agent.river
          env:
            - name: AGENT_MODE
              value: flow
          envFrom:
            - secretRef:
                name: grafana-agent-credentials
          ports:
            - name: grpc
              containerPort: 4317
            - name: http
              containerPort: 4318
          volumeMounts:
            - mountPath: /etc/agent-config/grafana-agent.river
              name: agent-config
              subPath: grafana-agent.river
      volumes:
        - name: agent-config
          configMap:
            name: agent-config
