# Uncomment the following line to deploy the application on a non-default namespace
#namespace: quickpizza

resources:
  - resources/deployments.yaml
  - resources/services.yaml
  # Uncomment one of the lines below if you want to enable telemetry. This will deploy the grafana agent and configure
  # QuickPizza to push traces to it.
  # - grafana-agent/cloud
  # - grafana-agent/local

# For telemetry functionality, change the following lines to match your configuration.
secretGenerator:
  - name: grafana-agent-credentials
    literals:
      # Required for grafana-agent/cloud to send telmetry to grafana cloud
      - GRAFANA_CLOUD_STACK=your-cloud-stack
      - GRAFANA_CLOUD_TOKEN=your-cloud-token
      # Required for grafana-agent/local to send to your local stack
      - TRACES_ENDPOINT=your-tempo-instance:443
      - METRICS_ENDPOINT=http://your-prometheus-remote-write-endpoint:9090/api/v1/write
      - PROFILES_ENDPOINT=your-pyroscope-instance

# You can use the following generator to add additional environment variables to all QuickPizza pods.
configMapGenerator:
  - name: quickpizza-env
    literals:
      # Trust all incoming TraceIDs for demo purposes.
      - QUICKPIZZA_TRUST_CLIENT_TRACEID=true
      # You can change other settings by adding entries to this list:
      #- CUSTOM_ENV=CUSTOM_VALUE
