apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app.k8s.io/name: opentelemetry-collector
spec:
  selector:
    app.k8s.io/name: opentelemetry-collector
  ports:
    - port: 4317
      name: grpc
      targetPort: grpc
    - port: 4318
      name: http
      targetPort: http
